#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

allowed_user="tianopo"
branch="$(git rev-parse --abbrev-ref HEAD)"
git_user=$(git config --global user.name)

if [ "$branch" = "main" ]; then
  if [ "$git_user" != "$allowed_user" ]; then
    echo "######################################" 
    echo "#"
    echo "# NÃO PERMITIDO COMMITS NA BRANCH MAIN"
    echo "#"
    echo "# REALIZE UM GIT PULL NA MAIN E CRIE UMA BRANCH A PARTIR DELA"
    echo "#"
    echo "######################################"
      exit 1
  fi
fi

# Executa o comando para formatar o código e captura a saída
format_output="$(npm run format 2>&1)"

# Verifica se houve erros ou avisos no comando format
if echo "$format_output" | grep -q 'error' || echo "$format_output" | grep -q 'warn'; then
  echo "######################################"
  echo "#"
  echo "# O comando 'yarn format' encontrou erros ou avisos."
  echo "# Por favor, corrija-os antes de realizar o commit."
  echo "#"
  echo "######################################"
  exit 1
fi